configured_endpoints: 5
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/tembo%2Ftembo-abdb5e7aeb8b07d9911c8c02febcf94371bbd191130de8cefca1c41a4f2e0b78.yml
openapi_spec_hash: d007ee18b8bb26e439a0d0fe4d4abae3
config_hash: 8fba1d45a848bce88e9564ab8a960838
